package br.com.visao;

/**
 *
 * @author Roney Vila
 */

public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMinserir_cliente = new javax.swing.JMenuItem();
        jMalterar_cliente = new javax.swing.JMenuItem();
        jMlistar_cliente = new javax.swing.JMenuItem();
        jMdeletar_cliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMinserir_estoque = new javax.swing.JMenuItem();
        jMalterar_estoque = new javax.swing.JMenuItem();
        jMlistar_estoque = new javax.swing.JMenuItem();
        jMdeletar_estoque = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 193, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/delilogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(253, 193, 210));
        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jMenuBar1.setForeground(new java.awt.Color(64, 31, 40));
        jMenuBar1.setAlignmentY(0.8F);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu5.setBorder(null);
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/icons8-entrar-24.png"))); // NOI18N
        jMenu5.setText("Login");
        jMenu5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/icons8-senha-24.png"))); // NOI18N
        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenu1.setBorder(null);
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/icons8-usuário-24 (1).png"))); // NOI18N
        jMenu1.setText(" ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMinserir_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMinserir_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/inserir.png"))); // NOI18N
        jMinserir_cliente.setText("Inserir");
        jMinserir_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinserir_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMinserir_cliente);

        jMalterar_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMalterar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/alterar.png"))); // NOI18N
        jMalterar_cliente.setText("Alterar");
        jMalterar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalterar_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMalterar_cliente);

        jMlistar_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMlistar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/listar.png"))); // NOI18N
        jMlistar_cliente.setText("Listar");
        jMlistar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlistar_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMlistar_cliente);

        jMdeletar_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMdeletar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/deletar.png"))); // NOI18N
        jMdeletar_cliente.setText("Deletar");
        jMdeletar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMdeletar_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMdeletar_cliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/icons8-caixa-24.png"))); // NOI18N
        jMenu2.setText("Estoque");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMinserir_estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMinserir_estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/inserir.png"))); // NOI18N
        jMinserir_estoque.setText("Inserir");
        jMinserir_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinserir_estoqueActionPerformed(evt);
            }
        });
        jMenu2.add(jMinserir_estoque);

        jMalterar_estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMalterar_estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/alterar.png"))); // NOI18N
        jMalterar_estoque.setText("Alterar");
        jMalterar_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalterar_estoqueActionPerformed(evt);
            }
        });
        jMenu2.add(jMalterar_estoque);

        jMlistar_estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMlistar_estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/listar.png"))); // NOI18N
        jMlistar_estoque.setText("Listar");
        jMlistar_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMlistar_estoqueActionPerformed(evt);
            }
        });
        jMenu2.add(jMlistar_estoque);

        jMdeletar_estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMdeletar_estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/deletar.png"))); // NOI18N
        jMdeletar_estoque.setText("Deletar");
        jMdeletar_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMdeletar_estoqueActionPerformed(evt);
            }
        });
        jMenu2.add(jMdeletar_estoque);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(null);
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/icons8-carrinho-24.png"))); // NOI18N
        jMenu3.setText("Pedidos");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/inserir.png"))); // NOI18N
        jMenuItem2.setText("Inserir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/alterar.png"))); // NOI18N
        jMenuItem3.setText("Alterar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/listar.png"))); // NOI18N
        jMenuItem4.setText("Listar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/visao/deletar.png"))); // NOI18N
        jMenuItem5.setText("Deletar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMinserir_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinserir_clienteActionPerformed
        TelaClienteInserir ci = new TelaClienteInserir();
        ci.setVisible(true); 
    }//GEN-LAST:event_jMinserir_clienteActionPerformed

    private void jMalterar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalterar_clienteActionPerformed
        TelaClienteAlterar ca = new TelaClienteAlterar();
        ca.setVisible(true);
    }//GEN-LAST:event_jMalterar_clienteActionPerformed

    private void jMlistar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlistar_clienteActionPerformed
        TelaClienteListar cl = new TelaClienteListar();
        cl.setVisible(true);
    }//GEN-LAST:event_jMlistar_clienteActionPerformed

    private void jMdeletar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMdeletar_clienteActionPerformed
        TelaClienteDeletar cd = new TelaClienteDeletar();
        cd.setVisible(true);
    }//GEN-LAST:event_jMdeletar_clienteActionPerformed

    private void jMinserir_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinserir_estoqueActionPerformed
        TelaEstoqueInserir ei = new TelaEstoqueInserir();
        ei.setVisible(true);
    }//GEN-LAST:event_jMinserir_estoqueActionPerformed

    private void jMalterar_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalterar_estoqueActionPerformed
        TelaEstoqueAlterar ea = new TelaEstoqueAlterar();
        ea.setVisible(true);
    }//GEN-LAST:event_jMalterar_estoqueActionPerformed

    private void jMlistar_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMlistar_estoqueActionPerformed
        TelaEstoqueListar el = new TelaEstoqueListar();
        el.setVisible(true);
    }//GEN-LAST:event_jMlistar_estoqueActionPerformed
   
    private void jMdeletar_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMdeletar_estoqueActionPerformed
        TelaEstoqueDeletar ed = new TelaEstoqueDeletar();
        ed.setVisible(true);
    }//GEN-LAST:event_jMdeletar_estoqueActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaClientePedidoInserir pdi = new TelaClientePedidoInserir();
        pdi.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaClientePedidoApagar pdap = new TelaClientePedidoApagar();
        pdap.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaCliente_PedidoAlterar cpa = new TelaCliente_PedidoAlterar();
        cpa.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaClientePedidoListar cpl = new TelaClientePedidoListar();
        cpl.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMalterar_cliente;
    private javax.swing.JMenuItem jMalterar_estoque;
    private javax.swing.JMenuItem jMdeletar_cliente;
    private javax.swing.JMenuItem jMdeletar_estoque;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMinserir_cliente;
    private javax.swing.JMenuItem jMinserir_estoque;
    private javax.swing.JMenuItem jMlistar_cliente;
    private javax.swing.JMenuItem jMlistar_estoque;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
